### ISSUE TITLE
CSV Marker Data Issues

### ISSUE THREAD

**Issue by Moonbase59** [valentine195/obsidian-leaflet-plugin#27]
I had this map:
```
height: 500px
latitude: 51.133333
longitude: 10.416667
minZoom: 1
maxZoom: 18
defaultZoom: 5
```

After upgrading to 2.0.1, I had to change `latitude` to `lat` and `longitude` to `long` and it would only display after I put an `id:` in:
```
id: Germany
height: 500px
lat: 51.133333
long: 10.416667
minZoom: 1
maxZoom: 18
defaultZoom: 5
```

First thing I did was try the new export to CSV feature. The map now displays but it has not one marker in it anymore! I tried importing the CSV again but this doesn’t help.

How can I get my markers back?

Tried to modify the CSV but to no avail. Seems the plugin _keeps_ old markers forever, I have now 2 sets of the same locations (on export) and no means of deleting them. They got different GUIDs, though.

I would have expected that it doesn’t accumulate but export/import _all_ markers, i.e. if I would delete one in the CSV, it should also be gone on the map (after a new import).

The problem with creating new markers (in the CSV) would also be that I can’t create a GUID for them.

For me, the main reason for the CSV would be to _generate_ a list of markers (Friends & Family, favourite locations, etc.) with well-known GPS locations _outside_ Leaflet (because it’s much too complicated and OpenStreetMap not exact), then _import_ those and have them _appear_ on the map(s).

**Comment by valentine195** [comment]
Okay, the reason the markers disappear is because the "id" of the map changed. The markers should still be associated with the map in the data and come back if you remove field. I'll look into what's going on with the issue about not being able to change parameters.

**Comment by Moonbase59** [comment]
Yeah, that’s what I thought. The old map had exported names like `+Inbox/Leaflet Test.md/real` and whenever I created a new one (on the map, by clicking), it was exported as `+Inbox/Leaflet Test.md/Germany`, with an extra field "real" near the end.

So I tried replacing "/real" with "/Germany" in a text editor, and put a "real" in all the old entries that didn’t have one. Then I reimported the CSV but nothing showed up.

**Comment by valentine195** [comment]
> height: 500px
> latitude: 51.133333
> longitude: 10.416667
> minZoom: 1
> maxZoom: 18
> defaultZoom: 5

This map rendered without error for me when I changed latitude and longitude to lat and long. No need for an id field. Does that work? Additionally, I'm surprised that latitude: and longitude: even worked -- it's always been lat:/long:, so it was probably just pulling the defaults and ignoring those fields. I'll add a notice when there's unsupported parameters in the code block.

> The problem with creating new markers (in the CSV) would also be that I can’t create a GUID for them.

I haven't documented this feature yet, but the "id" of a marker can be anything (unique on that map). A GUID is just easiest for me to auto generate. In fact, if you leave it blank, a GUID will be generated.

**Comment by Moonbase59** [comment]
Good find. If I remove the `id: Germany` line, it now shows all the "old" markers, but as "default". Maybe this is because I changed my "User" marker type to "Friends" and it reverts to default. No problem with that.

I noticed, when changing all the names above from "…/real" to "…/Germany", re-imported the CSV and exported it again, they had all reverted to "/real"! This may be the reason why the map now works again when leaving the `id:` line out. (I assume you use `real` as kinda default.)

**Comment by valentine195** [comment]
Yes - "real" is a "real world" map.

I'm glad that the markers came back in. It should be possible to change the marker type in the CSV and re-import it and update them. I am planning on a bulk edit feature that will have a GUI to update all of the markers on a map in one place to make it easier to do this.

I'll document this (tomorrow probably - just wanted to make sure this issue wasn't a big bug I missed), but basically if you copy and add rows, then change the marker ID (to something unique on that map, it can be anything), then it will create a new marker. If the marker IDs are the same, it will overwrite the previous marker.

Sorry for the chaos!

**Comment by Moonbase59** [comment]
Okay, I’ll play around with the CSV stuff a while longer, thanks for implementing it anyway!

Still, we should find a means of erasing old stuff (without having to click hundreds of markers), maybe just erase all markers whenever a CSV is imported? Or introduce an option like "Erase all markers on this map".

I’ll try to leave the GUID field empty and see if I can create new ones or edit existing ones …

**Comment by valentine195** [comment]
The plugin does try to delete old data. It can be difficult to detect that a map instance has been removed from a note, though (and my implementation of that Obsidian API is probably not be the best, either). 

I agree though about removing old data. Once I add the bulk marker editing UI there will definitely be a "delete all" button.

**Comment by Moonbase59** [comment]
Great, thanks!

Do you think it possible that there is some odd caching stuff going on?
- I deleted 2 markers, went to another note, went back, and the two markers were back.
- I exported CSV, changed latitude for one entry by -3 (to see the change), and re-imported. Nothing changed, not even after restarting Obsidian. Only on the 3rd or 4th re-import id suddenly changed.

**Comment by Moonbase59** [comment]
I have a CSV entry with a quoted link (`Berlin, Weltzeituhr`) that doesn’t get imported:
```
People/Friends & Family/+Friends & Family TOC.md/real,Location,52.52134162768218,13.41327381161729,"Berlin, Weltzeituhr",,
```

**Comment by valentine195** [comment]
> I have a CSV entry with a quoted link (`Berlin, Weltzeituhr`) that doesn’t get imported:
> 
> ```
> People/Friends & Family/+Friends & Family TOC.md/real,Location,52.52134162768218,13.41327381161729,"Berlin, Weltzeituhr",,
> ```
> 
> When creating the same entry manually on the map, export creates an extra column! Instead of putting the text value into `"` like `"Berlin, Weltzeituhr"`. Text values should be quoted, also because in some countries (like Germany) the usual CSV field separator is often a semicolon, not a comma (because we use the comma as a decimal separator instead of the decimal point).

Fixed in 2.0.2.

**Comment by valentine195** [comment]
> * I exported CSV, changed latitude for one entry by -3 (to see the change), and re-imported. Nothing changed, not even after restarting Obsidian. Only on the 3rd or 4th re-import it suddenly changed.
> * I exported CSV, changed a link name, re-imported multiple times, and it won’t change. Also, on re-exporting the old name is back in the CSV.

I believe these issues were fixed in 2.0.2. Could you try it out and let me know?

**Comment by Moonbase59** [comment]
Export of "Berlin, Weltzeituhr" now writes a quoted entry on export and thus can be imported into spreadsheet apps.

Probably _all_ text type fields should be quoted?! Imagine I would now create folders containing a comma—that would break the 1st column, I think.

It still doesn’t work to change the lat/lon in the "Berlin, Weltzeituhr" entry (keeping the GUID from export intact) and then re-import.

**Comment by Moonbase59** [comment]
When playing around with all this CSV and map stuff, I found a new desperate need: Since so much data is location-based, and we all tend to use WGS-84 "Google-type" latitude,longitude pairs, it would be just great if
- instead of setting a marker by zooming around and trying to find a place,
- we could just copy-paste "lat,long" value pairs into some input field (ideally in the format Google Maps uses when you copy a location to the clipboard).

My front matter for people and places always uses
```
---
location: [51.133333,10.416667]
---
```
so these could also be easily copy-pasted into a map (or somehow _used_/_read_ even?).

**Comment by valentine195** [comment]
> My front matter for people and places always uses
> 
> ```
> ---
> location: [51.133333,10.416667]
> ---
> ```
> 
> so these could also be easily copy-pasted into a map (or somehow _used_/_read_ even?).

I actually just started playing with the Dataview plugin, and saw your post in [this topic](https://forum.obsidian.md/t/dataview-plugin-snippet-showcase/13673) that made me start thinking of ways to incorporate the frontmatter into this.

It's very easy to read the front matter of notes, so I think it should be simple if you point the map towards a note, it reads any defined frontmatter and creates it.

Your use case also gave me the idea to have the ability to point the map towards a _folder_, and auto-create markers for all of the notes within the folder.

As an aside, I started working on a UI to edit all of the markers on a map. It will essentially be a modal that displays a simple map view (no events/etc), and a table with all defined markers. Highlighting a marker will zoom the map to that location, and you will be able to bulk delete, add new markers, change Lat/Long, change the linked note, etc. I think it will vastly improve the marker experience. Hopefully I'll have it together this week.

> On the other hand, if right-clicking existing markers within a Leaflet map, it would show the coordinates and we could copy the coordinate set using only one copy-paste to be used elsewhere (Google Maps, Obsidian Notes, …)

Yeah, easily done.

**Comment by valentine195** [comment]
> Probably _all_ text type fields should be quoted?! Imagine I would now create folders containing a comma—that would break the 1st column, I think.

The CSV parsing is now being handled by an external module (I originally just wrote a quick parser, but I am not too familiar with the CSV spec). I decided to not turn on quoting _all_ fields, but I can. The parser _should_ be detecting any field that needs to be quoted and handling that itself.

> It still doesn’t work to change the lat/lon in the "Berlin, Weltzeituhr" entry (keeping the GUID from export intact) and then re-import.

Okay, that's definitely a bug. I'll look into it, sorry!

**Comment by Moonbase59** [comment]
No problem, happy for what you do already!

**Comment by Moonbase59** [comment]
I feel that somehow "decoupling" the map and markers from "hard-coded values" might be nice.

A user _will_ rename and move notes around, and probably even want to reference the same set of locations in another Leaflet map (or even the same map).

**Comment by valentine195** [comment]
Maybe a new map view type? :grin:

**Comment by Moonbase59** [comment]
Poor you … see what comes out of "just creating a map view for a game" … :rofl:

**Comment by valentine195** [comment]
Funny thing is I've worked on this plugin more than my DnD campaign 😳

**Comment by valentine195** [comment]
Yep, generic path overlays are possible:

https://leafletjs.com/examples/quick-start/example-overlays.html

I was actually already planning on working on this already, but want to get the marker stuff nailed down first.

**Comment by Moonbase59** [comment]
Absolutely. First things first. You’re now early enough with this plugin to maybe break the interface(s). This won’t easily be possible when thousands start actually _using_ it.

**Comment by Moonbase59** [comment]
Wow, you _are_fast! Trying 2.1.0:

The marker data in code block works just great, including using "unknown" marker types and then defaulting to the default marker type.

Did you include external links yet? Trying this always displays a "file name", consisting of the last part of the URL, up to next `/` and displaying "File name cannot contain any of the following characters: \ / :".

I tried these variants:
```
marker: Location,51.133333,10.416667,[[Mittelpunkt Deutschlands]]
```
Works just great.

```
marker: Location,51.133333,10.416667,[[Test|Charlie Brown]]
```
Works but shows `Test|Charlie Brown` in the popup when "Display Note Preview" is off. Preview on works correctly.

```
marker: Location,51.133333,10.416667,[[Test#Images]]
```
Works but shows `Test#Images` in the popup when "Display Note Preview" is off. Preview on works correctly (i.e., showing from the header "Images").

```
marker: Location,51.133333,10.416667,[Mittelpunkt Deutschlands](https://de.wikipedia.org/wiki/Mittelpunkte_Deutschlands)
```
- Preview off: Displays "Mittelpunkte_Deutschlands)"
- Preview on: Displays "[Mittelpunkt Deutschlands](https://de.wikipedia.org/wiki/Mittelpunkte_Deutschlands) is not created yet. Click to create."

```
marker: Location,51.133333,10.416667,https://de.wikipedia.org/wiki/Mittelpunkte_Deutschlands
```
- Preview off: Displays "Mittelpunkte_Deutschlands"
- Preview on: Displays "https://de.wikipedia.org/wiki/Mittelpunkte_Deutschlands is not created yet. Click to create."

It would be superb if all these could work:
- Naked Obsidian Wikilinks
- Obsidian Wikilinks with changed display text
- Obsidian Wikilinks with heading and block references
- Markdown-style links
- simple URIs

**Comment by Moonbase59** [comment]
> > It still doesn’t work to change the lat/lon in the "Berlin, Weltzeituhr" entry (keeping the GUID from export intact) and then re-import.
> 
> Okay, that's definitely a bug. I'll look into it, sorry!
> 
> EDIT: I believe this is fixed now. Can you verify?

Yep, it works now! :+1:

**Comment by valentine195** [comment]
Yeah, external links aren't supported. I don't think it would be difficult to add support for it, though.

Do you think it would be useful to create a "note preview window" with an embedded iframe when you hover an externally linked-marker?

> One could debate about exporting the immutable code block markers into the CSV, but I think it’s quite ok not to, as it is right now. Still, this behaviour should be eventually documented.

These markers aren't saved to the map instance because their data can't be changed in preview mode, so there's no need to track them when a map instance is destroyed - when the plugin re-creates the map, it just re-reads the immutable code block marker data and re-creates them as needed.

**Comment by Moonbase59** [comment]
Personally, I would have no use of iframeing an external link, but, well … some might. I actually usually switch preview off, since with many markers the popups get distracting—you can't see and possibly click other markers.

Immutable markers: Okay so the "feature" is we have a clean separation: Immutable markers per map, plus more "dynamic" markers from clicking around or importing CSV (or maybe later specify a file)—I like it.

**Comment by valentine195** [comment]
> ```
> marker: Location,51.133333,10.416667,[[Test|Charlie Brown]]
> ```
> 
> Works but shows `Test|Charlie Brown` in the popup when "Display Note Preview" is off. Preview on works correctly.

Fixed in 2.1.1. Note preview now finds the correct note, tooltip now displays the alt text.

> ```
> marker: Location,51.133333,10.416667,[[Test#Images]]
> ```
> 
> Works but shows `Test#Images` in the popup when "Display Note Preview" is off. Preview on works correctly (i.e., showing from the header "Images").

What would you prefer this displayed? `Test#Images` seems correct to me.

> ```
> marker: Location,51.133333,10.416667,[Mittelpunkt Deutschlands](https://de.wikipedia.org/wiki/Mittelpunkte_Deutschlands)
> ```
> 
> * Preview off: Displays "Mittelpunkte_Deutschlands)"
> * Preview on: Displays "[Mittelpunkt Deutschlands](https://de.wikipedia.org/wiki/Mittelpunkte_Deutschlands) is not created yet. Click to create."
> 
> ```
> marker: Location,51.133333,10.416667,https://de.wikipedia.org/wiki/Mittelpunkte_Deutschlands
> ```
> 
> * Preview off: Displays "Mittelpunkte_Deutschlands"
> * Preview on: Displays "https://de.wikipedia.org/wiki/Mittelpunkte_Deutschlands is not created yet. Click to create."

External links should work now, and display alt-text properly if provided.

**Comment by Moonbase59** [comment]
> > ```
> > marker: Location,51.133333,10.416667,[[Test#Images]]
> > ```
> > 
> > 
> > Works but shows `Test#Images` in the popup when "Display Note Preview" is off. Preview on works correctly (i.e., showing from the header "Images").
> 
> 
> What would you prefer this displayed? `Test#Images` seems correct to me.

I don’t know if it’s possible to re-use whatever Obsidian does for the links. In theory, I’d personally prefer your version, but this is outweighed by my wish to keep "same things same", because it makes it easier for users to recognize things.

The Obsidian default theme uses `Test > Images` for these (and `Test > ^c680f0` for block links).

**Comment by Moonbase59** [comment]
Quick test with 2.1.1:

```
marker: Location,51.133333,10.416667,[[Test|Charlie Brown]]
```
Looks ok but creates a new note `Test|Charlie Brown` when clicking, instead of opening `Test`.
Moreover, when trying to delete `Test|Charlie Brown`, Obsidian 0.11.13 exposes an odd bug: "File already exists".

```
marker: Location,51.133333,10.416667,https://de.wikipedia.org/wiki/Mittelpunkte_Deutschlands
```
works, but displays a `t` only as popup text.

**Comment by valentine195** [comment]
> Quick test with 2.1.1:
> 
> ```
> marker: Location,51.133333,10.416667,[[Test|Charlie Brown]]
> ```
> 
> Looks ok but creates a new note `Test|Charlie Brown` when clicking, instead of opening `Test`.
> Moreover, when trying to delete `Test|Charlie Brown`, Obsidian 0.11.13 exposes an odd bug: "File already exists".

This will be fixed in the next release.

> ```
> marker: Location,51.133333,10.416667,https://de.wikipedia.org/wiki/Mittelpunkte_Deutschlands
> ```
> 
> works, but displays a `t` only as popup text.

I noticed this last night, will be fixed in the next release.

**Comment by valentine195** [comment]
> The Obsidian default theme uses `Test > Images` for these (and `Test > ^c680f0` for block links).

Oh, yeah, that's doable. Will be in the next release.

**Comment by valentine195** [comment]
> > Quick test with 2.1.1:
> > ```
> > marker: Location,51.133333,10.416667,[[Test|Charlie Brown]]
> > ```
> > 
> > 
> > Looks ok but creates a new note `Test|Charlie Brown` when clicking, instead of opening `Test`.
> > Moreover, when trying to delete `Test|Charlie Brown`, Obsidian 0.11.13 exposes an odd bug: "File already exists".
> 
> This will be fixed in the next release.
> 
> > ```
> > marker: Location,51.133333,10.416667,https://de.wikipedia.org/wiki/Mittelpunkte_Deutschlands
> > ```
> > 
> > 
> > works, but displays a `t` only as popup text.
> 
> I noticed this last night, will be fixed in the next release.

Fixed in 3.0.0

> > The Obsidian default theme uses `Test > Images` for these (and `Test > ^c680f0` for block links).
> 
> Oh, yeah, that's doable. Will be in the next release.

Fixed in 3.0.0

**Comment by Moonbase59** [comment]
3.0.0 → IMPRESSIVE! Still testing, please see https://forum.obsidian.md/t/new-plugin-obsidian-leaflet-interactive-maps-in-notes/14752/48?u=moonbase59 in the meantime …

**Comment by Moonbase59** [comment]
All works great, except `Test > ^c680f0` is shown as `Test > > ^c680f0`.
Also good work on the CSV export quoting (Links like "Janssen, Frank-Eric" don’t break anymore).

**Comment by valentine195** [comment]
Darn, so close. Should be easily fixable!

Glad you like the new update!

**Comment by valentine195** [comment]
Also, just curious - did it convert the marker data for you correctly?

**Comment by Moonbase59** [comment]
Yay, it did! Great work! And I’m totally in love with the `markerFolder` feature … (almost) no need for external data anymore, it’s all in the YAML, and can be repurposed.

**Comment by valentine195** [comment]
Yeah, as long as the exporting and importing is working well, good with me.

**Comment by Moonbase59** [comment]
So bye-bye CSV Marker Data Issues. Don’t forget the circles and squares ;-)
